name: POI Workflow

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /apis/poi/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildImage
  displayName: Build POI Container Image
  jobs:
  - job: DockerBuild
    displayName: Docker Build and Push
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: 'AzContainerRegistry'
        repository: 'POI'
        command: 'buildAndPush'
        Dockerfile: 'apis/poi/web/Dockerfile'