name: POI (Point Of Interests) Deploy Container Image

trigger: none

# this is being defined in app-ci pipeline
resources:
  pipelines:
  - pipeline: 'POI (Point Of Interests) Deploy Container Image'
    source: 'POI (Point Of Interests) Build Container Image'
    trigger: 
      branches:
        include: 
          - main
          - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: openhacko291ndk2acr.azurecr.io/devopsoh/api-poi:$(Build.BuildId)
  azureSubscription: AzInternalSubscription
  # To ignore SSL error uncomment the following variable
  # VSTS_ARM_REST_IGNORE_SSL_ERRORS: true 

stages:
- stage: DeployContainer
  displayName: Deploy Container Image
  jobs:  
  - job: DeployContainer
    displayName: Deploy Container Image to Azure Web App for Container
    steps:
      - task: AzureWebAppContainer@1
        displayName: Azure Web App for Container
        inputs:
          azureSubscription: $(azureSubscription)
          resourceGroupName: 'openhacko291ndk2rg'
          appName: 'openhacko291ndk2poi'
          imageName: $(imageName)
          deployToSlotOrASE: true
          slotName: 'staging'
  - job: CreateWorkItem
    displayName: Create Work-Item on Container Deploy Failure
    dependsOn: DeployContainer
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        displayName: Create Work-Item on Container Deploy Failure
        inputs:
          workItemType: 'Issue'
          title: 'Container Deploy $(Build.BuildId) failed'