name: TRIPS Unit Testing

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main
      - master
  paths:
    include:
      - apis/trips/*

pool:
  vmImage: 'ubuntu-latest'

stages:
# - stage: BuildImage
#   displayName: Build TRIPS Container Image
#   jobs:
#   - job: DockerBuild
#     displayName: Docker Build and Push
#     steps: 
#     - task: Docker@2
#       displayName: 'Docker Build and Push'
#       inputs:
#         containerRegistry: 'AzContainerRegistry'
#         repository: 'devopsoh/api-trips'
#         command: 'buildAndPush'
#         Dockerfile: 'apis/trips/Dockerfile'
- stage: RunUnitTest
  displayName: Run Unit Tests
  jobs:  
  - job: RunUnitTest
    displayName: Run Unit Tests
    steps:
    - task: GoTool@0
      displayName: 'Use GO v1.11.1'
      inputs:
        version: '1.11.1'
    - task: Go@0
      displayName: 'Download GO Packages and Dependencies'
      inputs:
        command: 'get'
        workingDirectory: 'apis/trips'
    - task: Go@0
      displayName: 'Execute GO Unit Tests'
      inputs:
        command: 'test'
        arguments: '-v'
        workingDirectory: 'apis/trips/tests'
  - job: CreateWorkItem
    displayName: Create Work-Iitem on Unit Test Failure
    dependsOn: RunUnitTest
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        displayName: Create Work-Iitem on Unit Test Failure
        inputs:
          workItemType: 'Issue'
          title: 'Build $(Build.BuildId) failed'