name: TRIPS Unit Testing

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main
      - master
  paths:
    include:
      - apis/trips/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: RunUnitTestStage
  displayName: Run Unit Tests
  jobs:  
  - job: RunUnitTestJob
    displayName: Run Unit Tests
    steps:
      - task: GoTool@0
        displayName: 'Use GO v1.11.1'
        inputs:
          version: '1.11.1'
      - task: Go@0
        displayName: 'Download GO Packages and Dependencies'
        inputs:
          command: 'get'
          workingDirectory: 'apis/trips'
      - task: Go@0
        displayName: 'Execute GO Unit Tests'
        inputs:
          command: 'test'
          arguments: '-v'
          workingDirectory: 'apis/trips/tests'
  - job: CreateWorkItem
    displayName: Create Work-Item on Unit Test Failure
    dependsOn: RunUnitTestJob
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        displayName: Create Work-Item on Unit Test Failure
        inputs:
          workItemType: 'Issue'
          title: 'Build $(Build.BuildId) failed'