name: USER-JAVA API Workflow

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /apis/user-java/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildImage
  displayName: Build USER-JAVA Container Image
  jobs:
  - job: DockerBuild
    displayName: Docker Build and Push
    steps: 
    - task: Docker@2
      displayName: 'Docker Build and Push'
      inputs:
        containerRegistry: 'AzContainerRegistry'
        repository: 'devopsoh/api-user-java'
        command: 'buildAndPush'
        Dockerfile: 'apis/user-java/Dockerfile'
- stage: UnitTests
  displayName: Execute Unit Tests
  jobs:
  - job: UnitTest
    displayName: USER-JAVA Unit Tests
    steps:
    - task: Maven@3
      displayName: Running Unit Tests
      inputs:
        mavenPomFile: 'apis/user-java/pom.xml'
        goals: 'test'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false