name: USER-JAVA Build Container Image

trigger: none

# this is being defined in app-ci pipeline
resources:
  pipelines:
  - pipeline: 'USER-JAVA Build Container Image'
    source: 'USER-JAVA Unit Testing'
    trigger: 
      branches:
        include: 
          - main
          - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: openhacko291ndk2acr.azurecr.io/devopsoh/api-user-java:$(Build.BuildId)
  azureSubscription: AzInternalSubscription
  # To ignore SSL error uncomment the following variable
  # VSTS_ARM_REST_IGNORE_SSL_ERRORS: true
  containerRegistry: AzContainerRegistry
  repository: devopsoh/api-user-java
  resourceGroupName: 'openhacko291ndk2rg'
  appName: openhacko291ndk2userjava

stages:
- stage: BuildAndPushStage
  displayName: Build and Push Container Image
  jobs:  
  - job: BuildAndPushJob
    displayName: Build and Push Container Image to Azure Container Registry (ACR)
    steps:
      - task: Docker@2
        displayName: Login to Azure Container Registry (ACR)
        inputs:
          command: login
          containerRegistry: $(containerRegistry)
      - task: Docker@2
        displayName: Build Container Image
        inputs:
          repository: $(containerRegistry)
          command: build
          Dockerfile: 'apis/user-java/Dockerfile'
          tags: $(Build.BuildId)
          # arguments: --secret id=mysecret,src=mysecret.txt
      - task: Docker@2
        displayName: Push Container Image to Azure Container Registry (ACR)
        inputs:
          containerRegistry: |
            $(containerRegistry)
          repository: $(containerRegistry)
          command: push
          tags: |
            $(Build.BuildId)
  - job: DeployContainerJob
    displayName: Deploy Container Image to Azure Web App for Container
    dependsOn: BuildAndPushJob
    condition: succeeded() # this job will only run if rununittest fails
    steps:
      - task: AzureWebAppContainer@1
        displayName: Azure Web App for Container
        inputs:
          azureSubscription: $(azureSubscription)
          resourceGroupName: $(resourceGroupName)
          appName: $(appName)
          imageName: $(imageName)
          deployToSlotOrASE: true
          slotName: 'staging'
  - job: CreateWorkItemJob
    displayName: Create Work-Item on Build and Push Failure
    dependsOn: BuildAndPushJob
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        displayName: Create Work-Item on Build and Push Failure
        inputs:
          workItemType: 'Issue'
          title: 'Build and Push $(Build.BuildId) failed'