name: USER-PROFILE Unit Testing

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main
      - master
  paths:
    include:
      - apis/userprofile/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: RunUnitTestStage
  displayName: Run Unit Tests
  jobs:  
  - job: RunUnitTestJob
    displayName: Run Unit Tests
    steps:
      - task: Npm@1
        displayName: 'NPM Install'
        inputs:
          command: 'install'
          workingDir: 'apis/userprofile'
      - task: Npm@1
        displayName: 'Execute NPM Unit Tests'
        inputs:
          command: 'custom'
          workingDir: 'apis/userprofile'
          customCommand: 'run test'
      - task: Npm@1
        displayName: 'Collect NPM Code Coverage'
        inputs:
          command: 'custom'
          workingDir: 'apis/userprofile'
          customCommand: 'run cover'
      
  - job: CreateWorkItemJob
    displayName: Create Work-Item on Unit Test Failure
    dependsOn: RunUnitTestJob
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        displayName: Create Work-Item on Unit Test Failure
        inputs:
          workItemType: 'Issue'
          title: 'Build $(Build.BuildId) failed'