name: USER-JAVA Unit Testing

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main
      - master
  paths:
    include:
      - apis/user-java/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: RunUnitTest
  displayName: Run Unit Tests
  jobs:  
  - job: RunUnitTest
    displayName: Run Unit Tests
    steps:
      - task: Maven@3
        displayName: 'Build USER-JAVA'
        inputs:
          mavenPomFile: 'apis/user-java/pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: Maven@3
        displayName: 'Execute JAVA Unit Tests'
        inputs:
          mavenPomFile: 'apis/user-java/pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
  - job: CreateWorkItem
    displayName: Create Work-Iitem on Unit Test Failure
    dependsOn: RunUnitTest
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        displayName: Create Work-Iitem on Unit Test Failure
        inputs:
          workItemType: 'Issue'
          title: 'Build $(Build.BuildId) failed'