trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: WhiteSource@20
  inputs:
    projectName: 'AZDO_OpenHack-DevOps 2.0'
    # configuration: |
    #   npm.resolveDependencies=true
    #   maven.resolveDependencies=true